In [1]:
import pandas as pd
import numpy as np

In [2]:

df1 = pd.read_csv(r"C:\Users\Tim\OneDrive\Desktop\thesis\bigquerydata\aggregated_data_202203.csv")

In [3]:
df1.shape

(3975399, 4)

In [5]:
df1.head(20)

,user_login,event_dates,event_types,event_counts
0,0--key,['2022-03-22'],['PushEvent'],1
1,0-000,"['2022-03-06', '2022-03-06', '2022-03-06']","['PushEvent', 'PushEvent', 'ForkEvent']",3
2,0-001-0,['2022-03-15'],['PushEvent'],1
3,0-0Bruh,"['2022-03-06', '2022-03-06']","['CreateEvent', 'CreateEvent']",2
4,0-0devJSH,"['2022-03-02', '2022-03-02', '2022-03-02', '20...","['ForkEvent', 'ForkEvent', 'PushEvent', 'PushE...",4
5,0-1-2-3-4,"['2022-03-17', '2022-03-17', '2022-03-17', '20...","['ForkEvent', 'ForkEvent', 'ForkEvent', 'ForkE...",35
6,0-173,['2022-03-11'],['ForkEvent'],1
7,0-1Byte,"['2022-03-08', '2022-03-05', '2022-03-05', '20...","['CreateEvent', 'CreateEvent', 'PushEvent', 'C...",4
8,0-1CxH,"['2022-03-27', '2022-03-27']","['CreateEvent', 'CreateEvent']",2
9,0-2-1,"['2022-03-12', '2022-03-26', '2022-03-07', '20...","['PushEvent', 'PushEvent', 'CreateEvent', 'Pus...",10
10,0-8-15,"['2022-03-09', '2022-03-10', '2022-03-17', '20...","['PushEvent', 'PushEvent', 'PushEvent', 'PushE...",5
11,0-9-10-12,"['2022-03-03', '2022-03-04', '2022-03-04', '20...","['PushEvent', 'PushEvent', 'PushEvent', 'PushE...",4
12,0-9527,['2022-03-29'],['ForkEvent'],1
13,0-ALIK,"['2022-03-17', '2022-03-17']","['PushEvent', 'PushEvent']",2
14,0-Alex-B,"['2022-03-31', '2022-03-28', '2022-03-31', '20...","['PushEvent', 'PushEvent', 'PushEvent', 'PushE...",7
15,0-BSCode,"['2022-03-31', '2022-03-31']","['CreateEvent', 'CreateEvent']",2
16,0-Captain,"['2022-03-05', '2022-03-05', '2022-03-05', '20...","['PullRequestEvent', 'PushEvent', 'PushEvent',...",59
17,0-Chan,"['2022-03-20', '2022-03-20']","['CreateEvent', 'CreateEvent']",2
18,0-Defalt-0,['2022-03-01'],['ForkEvent'],1
19,0-E,"['2022-03-12', '2022-03-13', '2022-03-22']","['ForkEvent', 'IssuesEvent', 'ForkEvent']",3

In [4]:
users_df = pd.read_csv(r'C:\Users\Tim\OneDrive\Desktop\thesis\users_in_all_months.csv')
users_in_all_months = users_df['user_login'].tolist()

# Convert users_df['user_login'] to a list if it's not already
users_in_all_months = users_df['user_login'].tolist()

# Filter df1 to only include rows where 'user_login' is in users_in_all_months
df1_filtered = df1[df1['user_login'].isin(users_in_all_months)]

df1_filtered.head()

,user_login,event_dates,event_types,event_counts
63,0-melkonyanma-0,"['2022-03-27', '2022-03-13', '2022-03-21', '20...","['PullRequestEvent', 'PushEvent', 'PushEvent',...",11
73,0-tae,"['2022-03-05', '2022-03-05', '2022-03-05', '20...","['PushEvent', 'PushEvent', 'PushEvent', 'PushE...",33
76,0-v-0,"['2022-03-19', '2022-03-24', '2022-03-04', '20...","['PushEvent', 'CreateEvent', 'PushEvent', 'Pus...",22
78,0-vortex,"['2022-03-12', '2022-03-11', '2022-03-06', '20...","['PushEvent', 'PullRequestEvent', 'PullRequest...",253
79,0-wiz-0,"['2022-03-26', '2022-03-08', '2022-03-26', '20...","['PushEvent', 'IssuesEvent', 'PushEvent', 'Pus...",49

In [7]:
df1_filtered.shape

(175585, 4)

In [8]:
import pandas as pd
from datetime import datetime

def process_events_without_literal_eval(df):
    df_copy = df.copy()  # Work on a copy to avoid SettingWithCopyWarning
    
    for index, row in df_copy.iterrows():
        new_dates = []
        new_types = []
        event_count_decrement = 0

        for date, event_type in zip(row['event_dates'], row['event_types']):
            # Check if the date is on or after March 22, 2022
            if datetime.strptime(date, '%Y-%m-%d') >= datetime(2022, 3, 22):
                new_dates.append(date)
                new_types.append(event_type)
            else:
                event_count_decrement += 1

        # Update the DataFrame with the modified lists and adjusted counts
        df_copy.at[index, 'event_dates'] = new_dates  # No need to convert to string
        df_copy.at[index, 'event_types'] = new_types
        df_copy.at[index, 'event_counts'] -= event_count_decrement

    return df_copy

# Apply the function
df1_filtered_processed = process_events_without_literal_eval(df1_filtered)

In [9]:
df1_filtered_processed.head()

,user_login,event_dates,event_types,event_counts
63,0-melkonyanma-0,"[2022-03-27, 2022-03-27]","[PullRequestEvent, PushEvent]",2
73,0-tae,"[2022-03-25, 2022-03-30, 2022-03-29, 2022-03-2...","[PushEvent, PushEvent, PushEvent, PushEvent, P...",5
76,0-v-0,"[2022-03-24, 2022-03-25, 2022-03-23, 2022-03-2...","[CreateEvent, PushEvent, PushEvent, CreateEven...",6
78,0-vortex,"[2022-03-25, 2022-03-25, 2022-03-28, 2022-03-2...","[PushEvent, PullRequestEvent, PushEvent, PushE...",19
79,0-wiz-0,"[2022-03-26, 2022-03-26, 2022-03-28, 2022-03-2...","[PushEvent, PushEvent, PullRequestEvent, PushE...",26

In [10]:
# Assuming df1_filtered is created by filtering or selecting from another DataFrame
# Make it an explicit copy to avoid SettingWithCopyWarning
df1_filtered = df1_filtered_processed.copy()

# Specified event types
event_types = ['PullRequestEvent', 'PushEvent', 'IssuesEvent', 'CreateEvent', 'ForkEvent']

# Use apply with lambda functions for each event type to count occurrences
for event in event_types:
    df1_filtered[event] = df1_filtered['event_types'].apply(lambda x: x.count(event))

# Now df1_filtered will have new columns for each of the event types with their respective counts

In [11]:
df1_filtered.head(50)

,user_login,event_dates,event_types,event_counts,PullRequestEvent,PushEvent,IssuesEvent,CreateEvent,ForkEvent
63,0-melkonyanma-0,"[2022-03-27, 2022-03-27]","[PullRequestEvent, PushEvent]",2,1,1,0,0,0
73,0-tae,"[2022-03-25, 2022-03-30, 2022-03-29, 2022-03-2...","[PushEvent, PushEvent, PushEvent, PushEvent, P...",5,0,5,0,0,0
76,0-v-0,"[2022-03-24, 2022-03-25, 2022-03-23, 2022-03-2...","[CreateEvent, PushEvent, PushEvent, CreateEven...",6,0,3,0,3,0
78,0-vortex,"[2022-03-25, 2022-03-25, 2022-03-28, 2022-03-2...","[PushEvent, PullRequestEvent, PushEvent, PushE...",19,9,9,0,1,0
79,0-wiz-0,"[2022-03-26, 2022-03-26, 2022-03-28, 2022-03-2...","[PushEvent, PushEvent, PullRequestEvent, PushE...",26,1,23,1,0,1
90,00-Evan,"[2022-03-23, 2022-03-23, 2022-03-25, 2022-03-3...","[PushEvent, IssuesEvent, IssuesEvent, IssuesEv...",18,0,4,13,1,0
110,0000000100000000,"[2022-03-22, 2022-03-22, 2022-03-25, 2022-03-2...","[ForkEvent, ForkEvent, ForkEvent, ForkEvent, F...",16,0,0,0,0,16
142,0000Blaze,[],[],0,0,0,0,0,0
143,0000OOOO0000,"[2022-03-27, 2022-03-25, 2022-03-25, 2022-03-3...","[PushEvent, PushEvent, PushEvent, PushEvent, P...",9,0,9,0,0,0
200,000744210,[],[],0,0,0,0,0,0
247,000paradox000,"[2022-03-28, 2022-03-22, 2022-03-28, 2022-03-2...","[CreateEvent, PushEvent, PullRequestEvent, Pul...",54,12,29,0,13,0
279,0011223344ravi,"[2022-03-29, 2022-03-28, 2022-03-28, 2022-03-2...","[CreateEvent, CreateEvent, CreateEvent, Create...",12,0,1,0,11,0
280,001123,"[2022-03-29, 2022-03-22, 2022-03-31, 2022-03-2...","[PushEvent, PushEvent, PullRequestEvent, PushE...",17,9,8,0,0,0
392,004Ajay,"[2022-03-27, 2022-03-27, 2022-03-27, 2022-03-2...","[PushEvent, PushEvent, PushEvent, PushEvent, P...",5,0,5,0,0,0
405,00575,"[2022-03-27, 2022-03-31, 2022-03-27, 2022-03-3...","[CreateEvent, CreateEvent, CreateEvent, Create...",14,0,0,0,14,0
502,007exe,"[2022-03-28, 2022-03-29, 2022-03-27, 2022-03-2...","[PushEvent, PushEvent, PushEvent, PushEvent, P...",7,0,7,0,0,0
526,007quake,[2022-03-28],[PushEvent],1,0,1,0,0,0
788,00pf00,"[2022-03-23, 2022-03-27, 2022-03-27, 2022-03-2...","[PushEvent, PushEvent, CreateEvent, PushEvent,...",22,1,17,0,4,0
798,00sapo,[],[],0,0,0,0,0,0
838,00ze-cyclone,"[2022-03-31, 2022-03-31, 2022-03-26, 2022-03-3...","[PushEvent, PullRequestEvent, PushEvent, PushE...",18,2,14,0,2,0
866,01000001-01101011,"[2022-03-31, 2022-03-31, 2022-03-31, 2022-03-3...","[PushEvent, PushEvent, PullRequestEvent, PushE...",7,1,6,0,0,0
913,0102JohnnyTd,"[2022-03-29, 2022-03-28, 2022-03-22, 2022-03-2...","[CreateEvent, CreateEvent, CreateEvent, Create...",9,0,4,0,5,0
961,01101sam,[],[],0,0,0,0,0,0
986,0118Add,"[2022-03-29, 2022-03-29, 2022-03-26, 2022-03-2...","[PushEvent, PushEvent, PushEvent, PushEvent, P...",273,37,225,0,7,4
992,011Jorge,"[2022-03-30, 2022-03-23, 2022-03-30, 2022-03-31]","[CreateEvent, PushEvent, CreateEvent, CreateEv...",4,0,1,0,3,0
1046,0131ryu,"[2022-03-28, 2022-03-29, 2022-03-23, 2022-03-2...","[PushEvent, PushEvent, PushEvent, CreateEvent,...",13,0,8,0,5,0
1051,013Edu,"[2022-03-25, 2022-03-22, 2022-03-22, 2022-03-2...","[CreateEvent, PushEvent, CreateEvent, CreateEv...",6,0,2,0,4,0
1062,014967,"[2022-03-28, 2022-03-26, 2022-03-27, 2022-03-3...","[PushEvent, PushEvent, PushEvent, PushEvent, P...",27,6,19,0,1,1
1084,01662024622,"[2022-03-28, 2022-03-28, 2022-03-26, 2022-03-3...","[CreateEvent, CreateEvent, PushEvent, CreateEv...",6,0,2,0,4,0
1242,01es,"[2022-03-30, 2022-03-24, 2022-03-30, 2022-03-3...","[PushEvent, PushEvent, PushEvent, PullRequestE...",11,2,7,1,1,0
1324,01soni247,"[2022-03-25, 2022-03-25, 2022-03-25]","[CreateEvent, PushEvent, PushEvent]",3,0,2,0,1,0
1353,01zulfi,"[2022-03-22, 2022-03-27, 2022-03-22, 2022-03-2...","[PushEvent, PushEvent, PushEvent, PushEvent, P...",69,28,29,9,3,0
1363,0202-D,"[2022-03-26, 2022-03-31, 2022-03-31, 2022-03-3...","[PullRequestEvent, PullRequestEvent, PushEvent...",7,3,3,0,1,0
1367,0202zc,"[2022-03-22, 2022-03-22, 2022-03-22]","[PushEvent, PushEvent, ForkEvent]",3,0,2,0,0,1
1406,0214sh7,"[2022-03-31, 2022-03-31]","[IssuesEvent, PushEvent]",2,0,1,1,0,0
1423,022022,[],[],0,0,0,0,0,0
1504,02Gqbriel,"[2022-03-28, 2022-03-26, 2022-03-30, 2022-03-3...","[ForkEvent, PushEvent, PushEvent, PushEvent, P...",10,0,7,0,2,1
1535,02danieljonas,"[2022-03-27, 2022-03-29, 2022-03-29, 2022-03-2...","[PushEvent, PushEvent, PushEvent, PushEvent, P...",114,2,99,0,13,0
1594,030,[],[],0,0,0,0,0,0
1655,0314Valen,[2022-03-24],[PushEvent],1,0,1,0,0,0
1676,0320kangk,"[2022-03-29, 2022-03-23, 2022-03-25, 2022-03-2...","[CreateEvent, CreateEvent, CreateEvent, PullRe...",15,7,3,0,5,0
1682,0323pin,"[2022-03-23, 2022-03-22, 2022-03-23, 2022-03-2...","[PushEvent, PushEvent, PushEvent, IssuesEvent,...",18,1,11,3,0,3
1776,03brainy-clicks,"[2022-03-30, 2022-03-27, 2022-03-30, 2022-03-2...","[CreateEvent, CreateEvent, CreateEvent, PushEv...",11,0,1,0,10,0
1780,03ce007,[],[],0,0,0,0,0,0
1823,04-26,"[2022-03-23, 2022-03-23, 2022-03-23, 2022-03-2...","[PushEvent, PushEvent, PushEvent, PushEvent, P...",11,0,11,0,0,0
1865,0417taehyun,"[2022-03-29, 2022-03-24, 2022-03-25, 2022-03-2...","[PushEvent, PushEvent, PushEvent, PushEvent, P...",14,0,14,0,0,0
1926,04Marcus,"[2022-03-26, 2022-03-26, 2022-03-31, 2022-03-2...","[PushEvent, PushEvent, PushEvent, PushEvent, P...",9,0,9,0,0,0
1953,04n0,"[2022-03-28, 2022-03-24, 2022-03-27, 2022-03-3...","[PushEvent, PushEvent, PushEvent, PushEvent, P...",14,0,14,0,0,0
1981,0502j,[],[],0,0,0,0,0,0
1996,050644zf,"[2022-03-29, 2022-03-31, 2022-03-30, 2022-03-3...","[PushEvent, PushEvent, IssuesEvent, PushEvent,...",5,0,4,1,0,0

In [23]:

df1_filtered.to_csv(r'C:\Users\Tim\OneDrive\Desktop\thesis\filtered_csv\03-2022-filter', index=False)

In [ ]:

"C:\Users\Tim\OneDrive\Desktop\thesis\aggregated_data_202204.csv"